<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Imagen de la INE (Lado trasero)_image-profile</name>
   <tag></tag>
   <elementGuidId>ffa39e55-18e8-4ed4-bfaf-01ae461ac550</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/form/div/div[4]/div/div[2]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.ineImg.ml-3 > img.image-profile</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image-profile</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>./assets/img/idcard.png?j2gvkk5r466j5r937i76770038emab1ymh800zvw6m91h5tv0k52c052025y</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mat-tab-content-0-0&quot;)/div[@class=&quot;mat-tab-body-content ng-trigger ng-trigger-translateTab&quot;]/div[@class=&quot;p-3 ng-star-inserted&quot;]/form[@class=&quot;kt-form kt-form--group-seperator-dashed ng-invalid ng-touched ng-dirty&quot;]/div[@class=&quot;kt-form__section kt-form__section--first&quot;]/div[@class=&quot;form-group kt-form__group row&quot;]/div[@class=&quot;mt-4 ml-3 ine&quot;]/div[@class=&quot;ineImg ml-3&quot;]/img[@class=&quot;image-profile&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-tab-body[@id='mat-tab-content-0-0']/div/div/form/div/div[4]/div/div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = './assets/img/idcard.png?j2gvkk5r466j5r937i76770038emab1ymh800zvw6m91h5tv0k52c052025y']</value>
   </webElementXpaths>
</WebElementEntity>
